FROM nginxinc/nginx-unprivileged:1.27-alpine

COPY nginx.frontend.conf /etc/nginx/conf.d/default.conf

COPY index.html /usr/share/nginx/html/index.html
COPY lk/ /usr/share/nginx/html/lk/
COPY services/ /usr/share/nginx/html/services/
COPY viewer/ /usr/share/nginx/html/viewer/
COPY assets/ /usr/share/nginx/html/assets/

USER 101
EXPOSE 8080
